// <auto-generated />
namespace URFX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration281020151117 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration281020151117));
        
        string IMigrationMetadata.Id
        {
            get { return "201510280547142_migration281020151117"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
