// <auto-generated />
namespace URFX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration11220157273 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration11220157273));
        
        string IMigrationMetadata.Id
        {
            get { return "201511021410286_migration11220157273"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
