// <auto-generated />
namespace URFX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201510141401445_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201510141401445_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201510150607032_201510141401445_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
