// <auto-generated />
namespace URFX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration14032016440pm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration14032016440pm));
        
        string IMigrationMetadata.Id
        {
            get { return "201603141113376_Migration14032016440pm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
